language: android
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA_HOME=$JAVA8_HOME
    - cp app/gradle.properties.sample app/gradle.properties
script:
    - ./gradlew clean build
